### PR TITLE
Remove paddle_id and paddle_email columns

### PR DESCRIPTION
**Pull request by driesvints**
After a thorough chat with Paddle on how to handle customer identification we've decided to remove the `paddle_id` and `paddle_email` columns from Cashier Paddle all together. The reasons for this are that Paddle discourages any usage of `user_id` (even though they document it in their API documentation). 

The main reason behind all this is that `user_id` on a resource (orders, subscriptions) can change at any moment's notice when Paddle support, for example, changes the email address on it (when they might have received a support request). There isn't any webhook sent for when this happens so Cashier won't know that these values have changed. Because of this it's impossible to keep track of these values within Cashier and we won't be able to keep them in sync.

Furthermore when a `user_id` on a subscription gets changed it basically gets attached to a different user within Paddle. It's therefor impossible to have multiple subscriptions on a single user from a Paddle perspective. However, because we can use `passthrough` on most API endpoints we can still make sure a database user can be associated to multiple subscriptions. The caveat here is that they might be identified as different users within Paddle per subscription. Therefor, retrieving information like a user's email address within Paddle should always be done through the subscription, rather than the Customer model.

These are huge caveats with quite some implications for Cashier Paddle. It's also impossible to retrieve all transactions for a single customer in one list. We've therefor removed this method from Cashier Paddle. We are however thinking of solving this differently in a follow-up PR which I'll work on this week.

This all is quite unfortunate but it's good that we caught this before we made the first official release.

Ps. one small but fortunate side effect from this is that it's now a bit less strict to worry about customer identification within Cashier Paddle. App developers won't need to worry about keeping email addresses in sync with Paddle anymore. And instead of letting app developers contact Paddle for email changes (or any other personal info updates), customers can do this themselves.

### CODE REVIEW

**Comment by alzaabi98** [comment]
Cashier-Paddle is  going to be the only tool in Laravel that can be used globally from anywhere in world unlike stripe (limited to certain countries) . We are all having big hope to see it complete and mimc all possibilities like stripe or other mature payments gateway .

This is really wired from paddle but as you mentioned it is good to discovered now rather later. I think it is important for subscribers to see all data . Things like subscriptions type , status, amount , previous payment date , next payment date, ability to swap plans, see transactions, apply coupon on new or existing subscriptions. To me all of these are mandatory data otherwise it will not as promised as I was hoping to . Thanks  all for your efforts and time to get this tool see the light as soon as possible .

**Comment by techguydev** [comment]
@driesvints  thanks for letting us know, it makes a lot of sense.

Is there a mini tutorial to keep in mind when updating our system to this change?

**Comment by driesvints** [comment]
@techguydev I'm gonna write a changelog for this but not sure if a full upgrade guide is worth writing atm.

**Comment by techguydev** [comment]
Thanks @driesvints  I already have it in production so I would love to lead those instructions

**Comment by driesvints** [comment]
@techguydev you should definitely not have this in production yet... The upcoming changes in beta two are going to greatly change the way the package works.

**Pull request merged**
